export const STILL_BUTTONS = [
  {
    slotId: "still-1",
    id: "fn1",
    label: "Fn1ボタン",
    short: "Fn1",
    panel: "front",
    x: 43.5,
    y: 44.5,
    labelX: 27.0,
    labelY: 44.5,
  },
  {
    slotId: "still-2",
    id: "fn2",
    label: "Fn2ボタン",
    short: "Fn2",
    panel: "front",
    x: 43.5,
    y: 52.0,
    labelX: 27.0,
    labelY: 52.0,
  },
  {
    slotId: "still-3",
    id: "fn3",
    label: "Fn3ボタン",
    short: "Fn3",
    panel: "front",
    x: 43.5,
    y: 60.0,
    labelX: 27.0,
    labelY: 60.0,
  },
  {
    slotId: "still-4",
    id: "v_fn",
    label: "縦位置Fnボタン",
    short: "V-Fn",
    panel: "back",
    x: 23.0,
    y: 44.0,
    labelX: 13.0,
    labelY: 40.0,
  },
  {
    slotId: "still-5",
    id: "v_iso",
    label: "縦位置ISO感度ボタン",
    short: "V-ISO",
    panel: "back",
    x: 30.0,
    y: 49.0,
    labelX: 12.0,
    labelY: 46.0,
  },
  {
    slotId: "still-6",
    id: "focus_mode",
    label: "フォーカスモードボタン",
    short: "FM",
    panel: "front",
    x: 79.0,
    y: 52.0,
    labelX: 87.0,
    labelY: 51.0,
  },
  {
    slotId: "still-7",
    id: "protect_fn4",
    label: "プロテクト/Fn4ボタン",
    short: "Fn4",
    panel: "back",
    x: 28.0,
    y: 41.0,
    labelX: 19.0,
    labelY: 36.0,
  },
  {
    slotId: "still-8",
    id: "af_on",
    label: "AF-ONボタン",
    short: "AF-ON",
    panel: "back",
    x: 70.0,
    y: 38.0,
    labelX: 68.0,
    labelY: 30.0,
  },
  {
    slotId: "still-9",
    id: "sub_selector_center",
    label: "サブセレクター中央",
    short: "Sub",
    panel: "back",
    x: 69.0,
    y: 43.5,
    labelX: 78.0,
    labelY: 34.0,
  },
  {
    slotId: "still-10",
    id: "disp",
    label: "DISPボタン",
    short: "DISP",
    panel: "back",
    x: 61.0,
    y: 41.0,
    labelX: 56.0,
    labelY: 32.0,
  },
  {
    slotId: "still-11",
    id: "voice",
    label: "音声ボタン",
    short: "MIC",
    panel: "back",
    x: 63.5,
    y: 81.0,
    labelX: 64.0,
    labelY: 88.0,
  },
  {
    slotId: "still-12",
    id: "ok",
    label: "OKボタン",
    short: "OK",
    panel: "back",
    x: 69.0,
    y: 54.0,
    labelX: 78.0,
    labelY: 52.0,
  },
  {
    slotId: "still-13",
    id: "wb",
    label: "WBボタン",
    short: "WB",
    panel: "back",
    x: 58.0,
    y: 81.0,
    labelX: 54.0,
    labelY: 92.0,
  },
  {
    slotId: "still-14",
    id: "qual",
    label: "QUALボタン",
    short: "QUAL",
    panel: "back",
    x: 52.0,
    y: 82.0,
    labelX: 48.0,
    labelY: 92.0,
  },
  {
    slotId: "still-15",
    id: "v_multi_center",
    label: "縦位置マルチセレクター中央",
    short: "V-SEL",
    panel: "back",
    x: 62.0,
    y: 79.0,
    labelX: 62.0,
    labelY: 84.0,
  },
  {
    slotId: "still-16",
    id: "playback",
    label: "再生ボタン",
    short: "PLAY",
    panel: "back",
    x: 71.0,
    y: 61.0,
    labelX: 79.0,
    labelY: 65.0,
  },
  {
    slotId: "still-17",
    id: "movie_rec",
    label: "動画撮影ボタン",
    short: "REC",
    panel: "front",
    x: 41.5,
    y: 21.0,
    labelX: 41.5,
    labelY: 10.0,
  },
  {
    slotId: "still-18",
    id: "v_af_on",
    label: "縦位置AF-ONボタン",
    short: "V-AF",
    panel: "back",
    x: 74.0,
    y: 79.0,
    labelX: 82.0,
    labelY: 82.0,
  },
  {
    slotId: "still-19",
    id: "iso",
    label: "ISO感度ボタン",
    short: "ISO",
    panel: "front",
    x: 36.5,
    y: 21.0,
    labelX: 36.5,
    labelY: 10.0,
  },
  {
    slotId: "still-20",
    id: "exp_comp",
    label: "露出補正ボタン",
    short: "EV",
    panel: "front",
    x: 32.0,
    y: 21.0,
    labelX: 32.0,
    labelY: 10.0,
  },
  {
    slotId: "still-21",
    id: "flash_mode",
    label: "フラッシュモードボタン",
    short: "Flash",
    panel: "front",
    x: 38.5,
    y: 23.0,
    labelX: 38.5,
    labelY: 17.0,
  },
  {
    slotId: "still-22",
    id: "cmd_dial",
    label: "コマンドダイヤル",
    short: "CMD",
    panel: "front",
    x: 33.5,
    y: 31.5,
    labelX: 25.0,
    labelY: 32.0,
  },
  {
    slotId: "still-23",
    id: "lens_fn",
    label: "レンズのFnボタン",
    short: "L-Fn",
    visible: false,
  },
  {
    slotId: "still-24",
    id: "bkt",
    label: "BKTボタン",
    short: "BKT",
    panel: "front",
    x: 30.0,
    y: 28.0,
    labelX: 20.0,
    labelY: 29.0,
  },
  {
    slotId: "still-25",
    id: "lens_fn_ring_left",
    label: "レンズのFnリング（左回し）",
    short: "L-FnL",
    visible: false,
  },
  {
    slotId: "still-26",
    id: "lens_fn2",
    label: "レンズのFn2ボタン",
    short: "L-Fn2",
    visible: false,
  },
  {
    slotId: "still-27",
    id: "lens_memory_set",
    label: "レンズのメモリーセットボタン",
    short: "MEM",
    visible: false,
  },
  {
    slotId: "still-28",
    id: "lens_fn_ring_right",
    label: "レンズのFnリング（右回し）",
    short: "L-FnR",
    visible: false,
  },
  {
    slotId: "still-29",
    id: "lens_control_ring",
    label: "レンズのコントロールリング",
    short: "CTRL",
    visible: false,
  },
];

export const PLAYBACK_BUTTONS = [
  {
    slotId: "playback-1",
    id: "fn1",
    label: "Fn1ボタン",
    short: "Fn1",
    panel: "front",
    x: 43.5,
    y: 44.5,
    labelX: 27.0,
    labelY: 44.5,
  },
  {
    slotId: "playback-2",
    id: "fn2",
    label: "Fn2ボタン",
    short: "Fn2",
    panel: "front",
    x: 43.5,
    y: 52.0,
    labelX: 27.0,
    labelY: 52.0,
  },
  {
    slotId: "playback-3",
    id: "fn3",
    label: "Fn3ボタン",
    short: "Fn3",
    panel: "front",
    x: 43.5,
    y: 60.0,
    labelX: 27.0,
    labelY: 60.0,
  },
  {
    slotId: "playback-4",
    id: "v_fn",
    label: "縦位置Fnボタン",
    short: "V-Fn",
    panel: "back",
    x: 23.0,
    y: 44.0,
    labelX: 13.0,
    labelY: 40.0,
  },
  {
    slotId: "playback-5",
    id: "protect_fn4",
    label: "プロテクト/Fn4ボタン",
    short: "Fn4",
    panel: "back",
    x: 28.0,
    y: 41.0,
    labelX: 19.0,
    labelY: 36.0,
  },
  {
    slotId: "playback-6",
    id: "disp",
    label: "DISPボタン",
    short: "DISP",
    panel: "back",
    x: 61.0,
    y: 41.0,
    labelX: 56.0,
    labelY: 32.0,
  },
  {
    slotId: "playback-7",
    id: "voice",
    label: "音声ボタン",
    short: "MIC",
    panel: "back",
    x: 63.5,
    y: 81.0,
    labelX: 64.0,
    labelY: 88.0,
  },
  {
    slotId: "playback-8",
    id: "ok",
    label: "OKボタン",
    short: "OK",
    panel: "back",
    x: 69.0,
    y: 54.0,
    labelX: 78.0,
    labelY: 52.0,
  },
  {
    slotId: "playback-9",
    id: "wb",
    label: "WBボタン",
    short: "WB",
    panel: "back",
    x: 58.0,
    y: 81.0,
    labelX: 54.0,
    labelY: 92.0,
  },
  {
    slotId: "playback-10",
    id: "qual",
    label: "QUALボタン",
    short: "QUAL",
    panel: "back",
    x: 52.0,
    y: 82.0,
    labelX: 48.0,
    labelY: 92.0,
  },
  {
    slotId: "playback-11",
    id: "v_multi",
    label: "縦位置マルチセレクター",
    short: "V-SEL",
    panel: "back",
    x: 62.0,
    y: 79.0,
    labelX: 62.0,
    labelY: 84.0,
  },
  {
    slotId: "playback-12",
    id: "playback",
    label: "再生ボタン",
    short: "PLAY",
    panel: "back",
    x: 71.0,
    y: 61.0,
    labelX: 79.0,
    labelY: 65.0,
  },
  {
    slotId: "playback-13",
    id: "main_cmd_dial",
    label: "メインコマンドダイヤル",
    short: "Main",
    panel: "back",
    x: 72.0,
    y: 35.0,
    labelX: 88.0,
    labelY: 24.0,
  },
  {
    slotId: "playback-14",
    id: "sub_cmd_dial",
    label: "サブコマンドダイヤル",
    short: "Sub",
    panel: "back",
    x: 69.0,
    y: 43.5,
    labelX: 78.0,
    labelY: 34.0,
  },
  {
    slotId: "playback-15",
    id: "movie_rec",
    label: "動画撮影ボタン",
    short: "REC",
    panel: "front",
    x: 41.5,
    y: 21.0,
    labelX: 41.5,
    labelY: 10.0,
  },
  {
    slotId: "playback-16",
    id: "exp_comp",
    label: "露出補正ボタン",
    short: "EV",
    panel: "front",
    x: 32.0,
    y: 21.0,
    labelX: 32.0,
    labelY: 10.0,
  },
  {
    slotId: "playback-17",
    id: "iso",
    label: "ISO感度ボタン",
    short: "ISO",
    panel: "front",
    x: 36.5,
    y: 21.0,
    labelX: 36.5,
    labelY: 10.0,
  },
  {
    slotId: "playback-18",
    id: "bkt",
    label: "BKTボタン",
    short: "BKT",
    panel: "front",
    x: 30.0,
    y: 28.0,
    labelX: 20.0,
    labelY: 29.0,
  },
  {
    slotId: "playback-19",
    id: "flash_mode",
    label: "フラッシュモードボタン",
    short: "Flash",
    panel: "front",
    x: 38.5,
    y: 23.0,
    labelX: 38.5,
    labelY: 17.0,
  },
  {
    slotId: "playback-20",
    id: "lens_fn2",
    label: "レンズのFn2ボタン",
    short: "L-Fn2",
    visible: false,
  },
  {
    slotId: "playback-21",
    id: "lens_fn",
    label: "レンズのFnボタン",
    short: "L-Fn",
    visible: false,
  },
];
